### ISSUE TITLE
Research best practices for pagination in API responses

### ISSUE THREAD

**Issue by ivanmorales** [kountable/angular-kountable#14]
@eolexe

**Comment by ivanmorales** [comment]
Facebook does a `data` object and a `pagination` object to implement cursor-based pagination:
https://developers.facebook.com/docs/graph-api/using-graph-api#cursors
```
{
  "data": [
     ... Endpoint data is here
  ],
  "paging": {
    "cursors": {
      "after": "MTAxNTExOTQ1MjAwNzI5NDE=",
      "before": "NDMyNzQyODI3OTQw"
    },
    "previous": "https://graph.facebook.com/me/albums?limit=25&amp;before=NDMyNzQyODI3OTQw"
    "next": "https://graph.facebook.com/me/albums?limit=25&amp;after=MTAxNTExOTQ1MjAwNzI5NDE="
  }
}
```

**Comment by eolexe** [comment]
@ivanmorales not sure that cursors suite our case, that could be just over engineering for us. What benefits are you overseeing ?

**Comment by ivanmorales** [comment]
Twitter also adds their paging meta data to the response object:
https://dev.twitter.com/rest/reference/get/lists/members

**Comment by ivanmorales** [comment]
Here's a good stackoverflow discussion that talks about including paging metadata in the response:
http://stackoverflow.com/questions/12168624/pagination-response-payload-from-a-restful-api

> ReSTful APIs are consumed primarily by other systems, which is why I put paging data in the response headers. However, some API consumers may not have direct access to the response headers, or may be building a UX over your API, so providing a way to retrieve (on demand) the metadata in the JSON response is a plus.

**Comment by ivanmorales** [comment]
@eolexe I'm not thinking of using cursors to page data, only the idea of including a high-level metadata object in the response instead of in HTTP headers.  (Although the more I read the better I like the idea of cursor based paging) There seems to be a standard for `Links`, but none for **totals** in header response.  The best one I've seen is `X-Total-Count`.

I also forgot to bring up the idea of **sorting** on this same request.  Because paging will be done on the API, sorting must be done there as well.
