### ISSUE TITLE
Don't allow Chat on Project Page to send empty messages

### ISSUE THREAD

**Issue by jkalderonkiros** [kountable/angular-kountable#28]
## Issue Workflow

- [x] Issue ready for Project Manager Review by @eolexe @damengilland
- [ ] Issue ready for Estimation
- [ ] Issue ready for Prioritization & Approval by @jefftulsa
## User Story

As a (PERSONA), I (NEED OR WANT) to (ABILITY OR ACTION), in order to (BENEFIT). 
## Steps to Reproduce / Test

As a user on browser follow these steps... 
1. Open admin.kountable.com
2. Open projects page
3. Open random project
4. Navigate to chat

_Actual result_ Send message button could be used, sending empty message 
## Annotated Wireframes / Screenshots

![Screen Shot 2016-08-17 at 10:40 PM](http://marker.screenshots.prod.s3.amazonaws.com/a34202f98381467aaf1e500029d7572f-1471473441589.png)

**Source URL** :arrow_right: [http://admin.kountable.com/#/project/55...](http://admin.kountable.com/#/project/553/details)
## Acceptance Criteria / Expected Behavior

- Send message button should be disabled if there no text in text field.
## Special Testing Needs

- [x] None identified at this time.
## Dependencies

- [x] None identified at this time.
## Other Notes / Files

# Proposed Task
- [ ] ...

**Comment by Kirikami** [comment]
Issue  was fixed, tested on all envs
